# Service to request gripper opening or closure
# Request constants
uint8 IDLE=0
uint8 NAVIGATION=1
uint8 INTERACTION=2
uint8 OPEN_GRIPPER=3
uint8 CLOSE_GRIPPER=4
uint8 ABORT=5
# Request fields
uint8 state
---
bool successful_request
