#
# ComposableNode should not be nested with node name and namespace
#
image_transport: 'raw'  # image format: "raw" or "compressed"
family: '36h11'         # tag family name: 16h5, 25h9, 36h11, Standard41h12
size: 0.16           # default tag edge size in meter
threads: 4
max_hamming: 0          # maximum allowed hamming distance (corrected bits)
z_up: true              # rotate about x-axis to have Z pointing upwards
decimate: 1.0           # decimate resolution for quad detection
blur: 1.0               # sigma of Gaussian blur for quad detection
refine-edges: 1         # snap to strong gradients
debug: 0                # write additional debugging images to current working directory

# (optional) list of tags
# If defined, 'frames' and 'sizes' must have the same length as 'ids'.
tag_ids:    [3, 4]         # tag IDs for which to publish transform
tag_frames: [human_tag, locobot_tag]   # frame names
tag_sizes:  [0.16, 0.16]     # tag-specific edge size, overrides the default 'size'