kinect_node:
  ros__parameters:
    # Please note that the 'a' inserted in the serial number is only possible because
    # of fixes in the azure_kinect_ros_driver package that delete all the non numeric components
    # of the string. If you are using the original package, you should use the original serial number.
    
    sensor_sn: 'a000071601712'  # Serial number of the camera 'k02'
    depth_enabled: false
    rgb_point_cloud: false
    color_enabled: true
    color_resolution: '1080P'
    fps: 30
    point_cloud: false
    camera_namespace: 'k02' # 'k01' or 'k02'
    required: true


map_tf:
  ros__parameters:
    x: 0.092
    y: 0.340
    z: 3.743
    roll: -2.354
    pitch: 0.752
    yaw: 2.517
    # Note: In the launch file a prefix corresponding to the camera_namespace +'/' is added to the frame_id
    frame_id: 'rgb_camera_link'
    child_frame_id: 'map'